def PatternCount(Text, Pattern):
    count = 0
    for i in range(0, (len(Text) - len(Pattern) + 1)):
        if Text[i:i + len(Pattern)] == Pattern:
            count = count + 1
    return count


Input = "CCTCACCTTTAATAGTGTACGTTTTCACCTCACCTTACGCCAGCTTCCTCACCTTACGCCAGCTTTAATAGTGTATTTTCTTCCACGTTTTCAACGTTTTCACCTCACCTTACGTTTTCAATTTTCTTCCCCTCACCTTATTTTCTTCCTAATAGTGTCCTCACCTTTAATAGTGTATTTTCTTCCCCTCACCTTCCTCACCTTCCTCACCTTACGCCAGCTTACGTTTTCATAATAGTGTTAATAGTGTACGTTTTCAACGCCAGCTTCCTCACCTTACGCCAGCTTTAATAGTGTATTTTCTTCCACGTTTTCAACGTTTTCACCTCACCTTCCTCACCTTCCTCACCTTACGCCAGCTTTAATAGTGTACGCCAGCTTACGCCAGCTTATTTTCTTCCCCTCACCTTTAATAGTGTACGCCAGCTTACGTTTTCACCTCACCTTACGCCAGCTTACGTTTTCAACGTTTTCATAATAGTGTACGCCAGCTTATTTTCTTCCACGTTTTCAATTTTCTTCCCCTCACCTTACGTTTTCAACGCCAGCTTTAATAGTGTTAATAGTGTTAATAGTGTACGTTTTCAATTTTCTTCCCCTCACCTTCCTCACCTTACGTTTTCAATTTTCTTCCCCTCACCTTTAATAGTGTATTTTCTTCCATTTTCTTCCATTTTCTTCCCCTCACCTTCCTCACCTTTAATAGTGTTAATAGTGTTAATAGTGTCCTCACCTTCCTCACCTTATTTTCTTCCACGTTTTCAACGCCAGCTTATTTTCTTCCCCTCACCTTATTTTCTTCCTAATAGTGTCCTCACCTTTAATAGTGTCCTCACCTTCCTCACCTTACGTTTTCAATTTTCTTCCATTTTCTTCCACGTTTTCATAATAGTGTATTTTCTTCCACGCCAGCTTTAATAGTGTTAATAGTGTCCTCACCTTTAATAGTGT"


def FrequentWords(Text, k):
    maxcount = 0
    patternlength = int(k)
    FrequentPattern = []
    for i in range(0, (len(Text) - patternlength + 1)):
        if PatternCount(Text, Text[i:i + patternlength]) > maxcount:
            maxcount = PatternCount(Text, Text[i:i + patternlength])
            FrequentPattern = []
            FrequentPattern.append(Text[i:i + patternlength])
        elif PatternCount(Text, Text[i:i + patternlength]) == maxcount and Text[i:i + patternlength] not in FrequentPattern:
            FrequentPattern.append(Text[i:i + patternlength])
    print(maxcount)
    return FrequentPattern


print(FrequentWords(Input, 11))